routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::group(['middleware' => ['role:superadministrator|administrator|user']], function() {
    
    Route::get('/', function () {
        return view('users.index');
    });

    Route::group(['prefix' => 'garage'], function() {
        Route::get('/', 'AlgorithmController@index');
        Route::get('/list', 'AlgorithmController@list')->name('garage.list');
        Route::post('/run/{id}', 'AlgorithmController@run')->name('garage.run');
        Route::get('/design', 'AlgorithmController@design')->name('garage.design');
    });
    Route::get('/users/credits', 'UserController@credits')->name('users.credits');
    Route::resource('/users', 'UserController');

    Route::group(['prefix' => 'race'], function() {
        Route::get('/', 'RaceController@index')->name('race.index');
        Route::get('/profiles', 'RaceController@profiles')->name('race.profiles');
    });

    Route::group(['prefix' => 'gamble'], function() {
        Route::get('/', 'GambleController@index');
        Route::get('/bet', 'GambleController@bet')->name('gamble.bet');
        Route::get('/winners', 'GambleController@winners')->name('gamble.winners');
    });
});

Route::get('/home', 'HomeController@index');
Route::get('/contact', 'Controller@contactus')->name('contact');

Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    // Password reset
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>{{ config('app.name', 'algostakes') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        
        @guest
        @else
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'algostakes') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        
                          
                            <li class="dropdown">
                                <a href="{{ route('garage.list') }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>Garage </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('garage.list') }}">Algorithm list</a></li>
                                    <li><a href="{{ route('garage.design') }}">Design Algorithm</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="{{ route('garage.list') }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>Race </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('race.index') }}">Race results</a></li>
                                    <li><a href="{{ route('race.profiles') }}">Profiles in race club</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="{{ route('garage.list') }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>Gamble </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('gamble.bet') }}">Bet algorithms</a></li>
                                    <li><a href="{{ route('gamble.winners') }}">Winners list</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('users.index') }}">Profile</a></li>
                                    <li><a href="{{ route('users.edit', Auth::user()->id) }}">Edit Profile</a></li>
                                    <li><a href="{{ route('users.credits') }}">Credits History</a></li>
                                    <li><a href="{{ route('contact') }}">Contact us</a></li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
        @endguest
        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>